### ISSUE TITLE
Port to C#

### ISSUE THREAD

**Issue by Zeffe** [Zeffe/FBLAdesktopApp2#1]
Looking like I'm going to have to port this over to C# unless I can figure out a way to statically link unmanaged DLLs so I can have a stand-alone exe in the final build. C# is probably the better option for building a form project.

**Comment by Cast324** [comment]
Can you not have a stand-alone build in vc++?

**Comment by Zeffe** [comment]
@Cast324 I tried but it's giving me issues because it needs a DLL and won't let me link the DLL because it's using CLR and CLR is what makes it vc++ so without it it's just normal C++ and would have to be entirely recoded. I think C# has very similar arguments and stuff so it might just be simpler to port it to C#.
